import turtle
turtle.color("red")
turtle.pensize(5)
turtle.speed(90)
turtle.bgcolor("white")

turtle.left(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.penup()
turtle.forward(90)
turtle.right(90)
turtle.pendown()
turtle.forward(90)
turtle.right(180)
turtle.forward(90)
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.penup()
turtle.forward(90)
turtle.right(90)
turtle.pendown()
turtle.forward(90)
turtle.right(180)
turtle.forward(90)
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.penup()
turtle.forward(90)
turtle.right(90)
turtle.pendown()
turtle.forward(90)
turtle.right(180)
turtle.forward(90)
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.penup()
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.right(90)
turtle.pendown()
for i in range(300):
    turtle.forward(15)
    turtle.right(5)




window.exitonclick()
